export const VIEWS = [
  { id: 'table',     label: 'Table'     },
  { id: 'timeline',  label: 'Timeline'  },
  { id: 'ranking',   label: 'Ranking'   },
  { id: 'gains',     label: 'Gains'     },
  { id: 'history',   label: 'History'   },
  { id: 'tags',      label: 'Tags'      },
  { id: 'scatter',   label: 'Scatter'   },
  { id: 'spider',    label: 'Spider'    },
  { id: 'velocity',  label: 'Velocity'  },
  { id: 'breakdown', label: 'Breakdown' },
  { id: 'trending',  label: 'Trending'  },
  { id: 'bump',      label: 'Bump'      },
  { id: 'lifespan',  label: 'Lifespan'  },
  { id: 'heatmap',   label: 'Heatmap'   },
  { id: 'activity',   label: 'Activity'   },
  { id: 'retention',  label: 'Thread Depth'  },
  { id: 'compare',    label: 'Compare'    },
]
